# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  society-mgmt for CRUD operations

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  EnvType:
    Description: Environment type.
    Default: development
    Type: String
    AllowedValues:
      - production
      - staging
      - development
    ConstraintDescription: must specify production, staging or development.

Conditions:
  CreateProdResources: !Equals
    - !Ref EnvType
    - production
  CreateStagingResources: !Equals
    - !Ref EnvType
    - staging
  CreateDevResources: !Equals
    - !Ref EnvType
    - development

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  createSocietyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: functions/create-society/dist
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: create society
      Environment:
        Variables:
          ENVIRONMENT:
            !If [
              CreateProdResources,
              production,
              !If [CreateStagingResources, staging, development],
            ]
      Events:
        ApiDevelopment:
          Type: HttpApi
          Condition: CreateDevResources
          Properties:
            Path: /society
            Method: POST
            ApiId: !Ref crudHttpApiDevelopment
        ApiStaging:
          Type: HttpApi
          Condition: CreateStagingResources
          Properties:
            Path: /society
            Method: POST
            ApiId: !Ref crudHttpApiStaging
        ApiProd:
          Type: HttpApi
          Condition: CreateProdResources
          Properties:
            ApiId: !Ref crudHttpApiProduction
            Path: /society
            Method: POST

  readSocietyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: functions/read-society/dist
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: read society
      Environment:
        Variables:
          ENVIRONMENT:
            !If [
              CreateProdResources,
              production,
              !If [CreateStagingResources, staging, development],
            ]
      Events:
        ApiDevelopment:
          Type: HttpApi
          Condition: CreateDevResources
          Properties:
            Path: /society/{proxy+}
            Method: GET
            ApiId: !Ref crudHttpApiDevelopment
        ApiStaging:
          Type: HttpApi
          Condition: CreateStagingResources
          Properties:
            Path: /society/{proxy+}
            Method: GET
            ApiId: !Ref crudHttpApiStaging
        ApiProd:
          Type: HttpApi
          Condition: CreateProdResources
          Properties:
            ApiId: !Ref crudHttpApiProduction
            Path: /society/{proxy+}
            Method: GET

  deleteSocietyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: functions/delete-society/dist
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: delete society
      Environment:
        Variables:
          ENVIRONMENT:
            !If [
              CreateProdResources,
              production,
              !If [CreateStagingResources, staging, development],
            ]
      Events:
        ApiDevelopment:
          Type: HttpApi
          Condition: CreateDevResources
          Properties:
            Path: /society/{society_id}
            Method: DELETE
            ApiId: !Ref crudHttpApiDevelopment
        ApiStaging:
          Type: HttpApi
          Condition: CreateStagingResources
          Properties:
            Path: /society/{society_id}/
            Method: DELETE
            ApiId: !Ref crudHttpApiStaging
        ApiProd:
          Type: HttpApi
          Condition: CreateProdResources
          Properties:
            ApiId: !Ref crudHttpApiProduction
            Path: /society/{society_id}/
            Method: DELETE

  updateSocietyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: functions/update-society/dist
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: update society data
      Environment:
        Variables:
          ENVIRONMENT:
            !If [
              CreateProdResources,
              production,
              !If [CreateStagingResources, staging, development],
            ]
      Events:
        ApiDevelopment:
          Type: HttpApi
          Condition: CreateDevResources
          Properties:
            Path: /society/{proxy+}/
            Method: POST
            ApiId: !Ref crudHttpApiDevelopment
        ApiStaging:
          Type: HttpApi
          Condition: CreateStagingResources
          Properties:
            Path: /society/{proxy+}/
            Method: POST
            ApiId: !Ref crudHttpApiStaging
        ApiProd:
          Type: Api
          Condition: CreateProdResources
          Properties:
            ApiId: !Ref crudHttpApiProduction
            Path: /society/{proxy+}/
            Method: POST

  # Add a lambda authorizer to authenticate api access
  crudHttpApiDevelopment:
    Type: AWS::Serverless::HttpApi
    Condition: CreateDevResources
    StageName: development
    Description: crud api for society management
    DisableExecuteApiEndpoint: false

  crudHttpApiStaging:
    Type: AWS::Serverless::HttpApi
    Condition: CreateDevResources
    StageName: staging
    Description: crud api for society management
    DisableExecuteApiEndpoint: false

  crudHttpApiProduction:
    Type: AWS::Serverless::HttpApi
    Condition: CreateDevResources
    StageName: production
    Description: crud api for society management
    DisableExecuteApiEndpoint: false

  # updateSocietyApiProd:
  #   Type: AWS::Serverless::Api
  #   Condition: CreateProdResources
  #   Properties:
  #     Tags:
  #       Name: update-society-api-production
  #     StageName: production
  #     Models:
  #       BodyValidate:
  #         type: object
  #         required:
  #           - template
  #           - params
  #           - from
  #           - subject
  #           - recipients
  #         properties:
  #           template:
  #             type: string
  #           params:
  #             type: object
  #           subject:
  #             type: string
  #           recipients:
  #             type: array
  #     Auth:
  #       DefaultAuthorizer: AWS_IAM
  #     MethodSettings:
  #       CachingEnabled: false
  #       MetricsEnabled: true
  #     GatewayResponses:
  #       ACCESS_DENIED:
  #         StatusCode: 404
  #         ResponseTemplates:
  #           'application/json': '{"error": not found }'
  #         ResponseParameters:
  #           Headers:
  #             Access-Control-Allow-Origin: "'*'"
  #       AUTHORIZER_FAILURE:
  #         StatusCode: 404
  #         ResponseTemplates:
  #           'application/json': '{"error": not found }'
  #         ResponseParameters:
  #           Headers:
  #             Access-Control-Allow-Origin: "'*'"
  #       UNAUTHORIZED:
  #         StatusCode: 404
  #         ResponseTemplates:
  #           'application/json': '{"error": not found }'
  #         ResponseParameters:
  #           Headers:
  #             Access-Control-Allow-Origin: "'*'"
